"""AI 预设的优质低价股票池，移植自 lanren-bg-api/.../stock-from-ai.js。"""

HK_QUALITY_VALUE_STOCKS = [
    {"code": "00700", "name": "腾讯控股"},
    {"code": "09988", "name": "阿里巴巴-W"},
    {"code": "03690", "name": "美团-W"},
    {"code": "01810", "name": "小米集团-W"},
    {"code": "01211", "name": "比亚迪股份"},
    {"code": "00388", "name": "香港交易所"},
    {"code": "01024", "name": "快手-W"},
    {"code": "09992", "name": "泡泡玛特"},
    {"code": "00981", "name": "中芯国际"},
    {"code": "09618", "name": "京东集团-SW"},
    {"code": "09999", "name": "网易-S"},
    {"code": "02015", "name": "理想汽车-W"},
    {"code": "02020", "name": "安踏体育"},
    {"code": "00883", "name": "中国海洋石油"},
    {"code": "00941", "name": "中国移动"},
    {"code": "01398", "name": "工商银行"},
    {"code": "03988", "name": "中国银行"},
    {"code": "00939", "name": "建设银行"},
    {"code": "02318", "name": "中国平安"},
    {"code": "01299", "name": "友邦保险"},
]

US_QUALITY_VALUE_STOCKS = [
    {"code": "AAPL", "name": "苹果"},
    {"code": "MSFT", "name": "微软"},
    {"code": "NVDA", "name": "英伟达"},
    {"code": "GOOGL", "name": "Alphabet Inc."},
    {"code": "AMZN", "name": "亚马逊"},
    {"code": "META", "name": "Meta Platforms Inc."},
    {"code": "TSLA", "name": "特斯拉"},
    {"code": "BRK.B", "name": "伯克希尔哈撒韦"},
    {"code": "LLY", "name": "礼来"},
    {"code": "AVGO", "name": "博通"},
    {"code": "V", "name": "Visa"},
    {"code": "JPM", "name": "摩根大通"},
    {"code": "WMT", "name": "沃尔玛"},
    {"code": "UNH", "name": "联合健康"},
    {"code": "XOM", "name": "埃克森美孚"},
    {"code": "JNJ", "name": "强生"},
    {"code": "MA", "name": "万事达"},
    {"code": "PG", "name": "宝洁"},
    {"code": "HD", "name": "家得宝"},
    {"code": "MRK", "name": "默克"},
    {"code": "COST", "name": "好市多"},
    {"code": "ABBV", "name": "艾伯维"},
    {"code": "CRM", "name": "赛富时"},
    {"code": "AMD", "name": "超威半导体"},
    {"code": "NFLX", "name": "奈飞"},
    {"code": "QCOM", "name": "高通"},
    {"code": "INTC", "name": "英特尔"},
    {"code": "MSTR", "name": "MicroStrategy"},
    {"code": "COIN", "name": "Coinbase"},
    {"code": "BABA", "name": "阿里巴巴"},
    {"code": "PDD", "name": "拼多多"},
]

CN_QUALITY_VALUE_STOCKS = [
    {"code": "600519", "name": "贵州茅台"},
    {"code": "300059", "name": "东方财富"},
    {"code": "000858", "name": "五粮液"},
    {"code": "600887", "name": "伊利股份"},
    {"code": "600036", "name": "招商银行"},
    {"code": "601318", "name": "中国平安"},
    {"code": "601628", "name": "中国人寿"},
    {"code": "300750", "name": "宁德时代"},
    {"code": "002594", "name": "比亚迪"},
    {"code": "601012", "name": "隆基绿能"},
    {"code": "600900", "name": "长江电力"},
    {"code": "000333", "name": "美的集团"},
    {"code": "000651", "name": "格力电器"},
    {"code": "601899", "name": "紫金矿业"},
    {"code": "600276", "name": "恒瑞医药"},
    {"code": "300760", "name": "迈瑞医疗"},
    {"code": "603288", "name": "海天味业"},
    {"code": "600030", "name": "中信证券"},
    {"code": "600028", "name": "中国石化"},
    {"code": "601857", "name": "中国石油"},
    {"code": "601088", "name": "中国神华"},
    {"code": "601398", "name": "工商银行"},
    {"code": "601288", "name": "农业银行"},
    {"code": "601988", "name": "中国银行"},
    {"code": "601939", "name": "建设银行"},
    {"code": "601668", "name": "中国建筑"},
    {"code": "002415", "name": "海康威视"},
    {"code": "000568", "name": "泸州老窖"},
    {"code": "600809", "name": "山西汾酒"},
    {"code": "300274", "name": "阳光电源"},
    {"code": "601111", "name": "中国国航"},
]


def all_quality_value_stocks() -> list[dict]:
    """合并三地股票池（去重在 flow 中处理）。"""
    return [
        *HK_QUALITY_VALUE_STOCKS,
        *US_QUALITY_VALUE_STOCKS,
        *CN_QUALITY_VALUE_STOCKS,
    ]
